export const navigationUrls = {
  index: '/',
  app: '/',
  login: '/auth/login',
  registration: '/auth/register',
  forgotPassword: '/auth/forgot-password',
  resetPassword: '/auth/reset-password',
  dashboard: '/dashboard',
  students: '/students',
  student: '/students/:id',
  schedule: '/schedule',
  settings: '/settings',
  analytics: '/analytics',
  groups: '/groups',
} as const;
